### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Plazmius** [firehawk89/CSharp-Lab1#1]
https://github.com/firehawk89/CSharp-Lab1/blob/58110c30722e312ac1148543877db9352a71d77a/Lab1/GameAccount.cs#L34-L37

Зайва перевірка. Краще в разі програшу гри ставити рейтинг 1 при відємних значеннях

https://github.com/firehawk89/CSharp-Lab1/blob/58110c30722e312ac1148543877db9352a71d77a/Lab1/GameAccount.cs#L54-L58

Гру буде додано до історії лише 1 гравця, хоча рейтинг змінився у обох

https://github.com/firehawk89/CSharp-Lab1/blob/58110c30722e312ac1148543877db9352a71d77a/Lab1/GameAccount.cs#L54-L58

Немає трекінгу ID ігор та автоматичної генерації

**Comment by firehawk89** [comment]
> https://github.com/firehawk89/CSharp-Lab1/blob/58110c30722e312ac1148543877db9352a71d77a/Lab1/GameAccount.cs#L34-L37
> 
> Зайва перевірка. Краще в разі програшу гри ставити рейтинг 1 при відємних значеннях
> 
> https://github.com/firehawk89/CSharp-Lab1/blob/58110c30722e312ac1148543877db9352a71d77a/Lab1/GameAccount.cs#L54-L58
> 
> Гру буде додано до історії лише 1 гравця, хоча рейтинг змінився у обох
> 
> https://github.com/firehawk89/CSharp-Lab1/blob/58110c30722e312ac1148543877db9352a71d77a/Lab1/GameAccount.cs#L54-L58
> 
> Немає трекінгу ID ігор та автоматичної генерації

Стосовно ID ігор мається на увазі, що для кожної гри має бути свій унікальний рандомно згенерований ID? І при пошуку гри за ID треба зробити так, щоб користувач зміг отримати інформацію про саму гру?

**Comment by Plazmius** [comment]
Не обов`язково рандомний. Це може бути int поле в класі Game яке присвоється в конструкторі. І статичне поле int, де буде вестисть глобальний лічильник для всіх ігор, і інкрементуватись при створенні нових екземплярів Game

**Comment by firehawk89** [comment]
> Не обов`язково рандомний. Це може бути int поле в класі Game яке присвоється в конструкторі. І статичне поле int, де буде вестисть глобальний лічильник для всіх ігор, і інкрементуватись при створенні нових екземплярів Game

Добре, зрозумів. Дякую!

**Comment by firehawk89** [comment]
Вніс всі необхідні зміни.

**Comment by Plazmius** [comment]
@firehawk89 дякую. роботу зараховано

P.S. я одразу не помітив, у вас GameCount проперті не потрібне. Для кожного аккаунту можна отримати кількість ігор через GameList.Count(), а у вас воно ще й статичне, тобто рахує кількість ігор для всіх аккаунтів

**Comment by firehawk89** [comment]
> 

Прибрав поле GameCount, додав можливість виводу кількості зіграних ігор для кожного гравця.
